version: '3.7'

services:
  
  consul-server:
    image: hashicorp/consul:1.10.0
    container_name: consul-server
    restart: always
    volumes:
     - ./server.json:/consul/config/server.json:ro
     - serverdata:/consul/data
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent"

  consul-client:
    image: hashicorp/consul:1.10.0
    container_name: consul-client
    restart: always
    volumes:
     - ./client.json:/consul/config/client.json:ro
     - clientdata:/consul/data
    networks:
      - consul
    command: "agent"
    
volumes:
  serverdata:
    name: serverdata
    external: false
  clientdata:
    name: clientdata
    external: false

networks:
  consul:
    driver: bridge

